[package]
name = "jio-cli"
version = "0.1.2"
edition.workspace = true
rust-version = "1.88"
publish.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "jio"
path = "src/main.rs"

[dependencies]
jio-client = { path = "../crates/jio-client" }
crossterm = "=0.29.0"
ratatui = { version = "=0.30.2", default-features = false, features = ["crossterm"] }

[lints]
workspace = true
