[package]
name = "jio-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
jio-client = { path = "../../crates/jio-client" }
pyo3 = { version = "=0.29.2", features = ["extension-module"] }

[lints]
workspace = true
