from typing import Optional

DEFAULT_COMMAND_TIMEOUT: int

class JioError(Exception): ...

class Session:
    session_id: str
    state: str
    runtime: str
    template_id: str
    core_sha256: str
    guest_ipv4: str
    ssh_port: int
    ssh_username: str
    ssh_host_public_key: str
    guest_ready_ns: int
    network_ready_ns: int
    ssh_ready_ns: int

class CommandResult:
    @property
    def exit_code(self) -> int: ...
    @property
    def success(self) -> bool: ...
    @property
    def stdout(self) -> bytes: ...
    @property
    def stderr(self) -> bytes: ...
    @property
    def stdout_text(self) -> str: ...
    @property
    def stderr_text(self) -> str: ...
    def raise_for_status(self) -> None: ...

class Vm:
    @property
    def id(self) -> str: ...
    @property
    def session(self) -> Session: ...
    def refresh(self) -> Session: ...
    def exec(
        self,
        command: str,
        *,
        input: Optional[bytes] = None,
        timeout: int = 120,
    ) -> CommandResult: ...
    def write_file(
        self,
        remote_path: str,
        contents: bytes,
        *,
        timeout: int = 120,
    ) -> None: ...
    def read_file(self, remote_path: str, *, timeout: int = 120) -> bytes: ...
    def destroy(self) -> None: ...

class Jio:
    def __init__(
        self,
        endpoint: Optional[str] = None,
        api_key: Optional[str] = None,
        state_dir: Optional[str] = None,
    ) -> None: ...
    @property
    def endpoint(self) -> str: ...
    def create(self, runtime: Optional[str] = None) -> Vm: ...
    def inspect(self, session_id: str) -> Session: ...
    def get(self, session_id: str) -> Session: ...
    def attach(self, session_id: str) -> Vm: ...
    def destroy(self, session_id: str) -> None: ...

Client = Jio

class AsyncVm:
    @property
    def id(self) -> str: ...
    @property
    def session(self) -> Session: ...
    async def refresh(self) -> Session: ...
    async def exec(
        self,
        command: str,
        *,
        input: Optional[bytes] = None,
        timeout: int = 120,
    ) -> CommandResult: ...
    async def write_file(
        self,
        remote_path: str,
        contents: bytes,
        *,
        timeout: int = 120,
    ) -> None: ...
    async def read_file(self, remote_path: str, *, timeout: int = 120) -> bytes: ...
    async def destroy(self) -> None: ...

class AsyncJio:
    def __init__(
        self,
        endpoint: Optional[str] = None,
        api_key: Optional[str] = None,
        state_dir: Optional[str] = None,
    ) -> None: ...
    @property
    def endpoint(self) -> str: ...
    async def create(self, runtime: Optional[str] = None) -> AsyncVm: ...
    async def inspect(self, session_id: str) -> Session: ...
    async def get(self, session_id: str) -> Session: ...
    async def attach(self, session_id: str) -> AsyncVm: ...
    async def destroy(self, session_id: str) -> None: ...
