/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Jio {
  constructor(options?: JioOptions | undefined | null)
  get endpoint(): string
  create(runtime?: string | undefined | null): Promise<Vm>
  inspect(sessionId: string): Promise<SessionInfo>
  get(sessionId: string): Promise<SessionInfo>
  attach(sessionId: string): Promise<Vm>
  destroy(sessionId: string): Promise<void>
}
export type JsJio = Jio

export declare class Vm {
  get id(): string
  get session(): SessionInfo
  refresh(): Promise<SessionInfo>
  exec(command: string, options?: ExecOptions | undefined | null): Promise<ExecResult>
  writeFile(remotePath: string, contents: Buffer, options?: OperationOptions | undefined | null): Promise<void>
  readFile(remotePath: string, options?: OperationOptions | undefined | null): Promise<Buffer>
  destroy(): Promise<void>
}
export type JsVm = Vm

export interface ExecOptions {
  input?: Buffer
  timeoutSeconds?: number
}

export interface ExecResult {
  exitCode: number
  success: boolean
  stdout: Buffer
  stderr: Buffer
}

export interface JioOptions {
  endpoint?: string
  apiKey?: string
  stateDir?: string
}

export interface OperationOptions {
  timeoutSeconds?: number
}

export interface SessionInfo {
  sessionId: string
  state: 'ready' | 'failed' | 'destroyed'
  runtime: string
  templateId: string
  coreSha256: string
  guestIpv4: string
  sshPort: number
  sshUsername: string
  sshHostPublicKey: string
  guestReadyNs: bigint
  networkReadyNs: bigint
  sshReadyNs: bigint
}
